
general.import = ["~/.config/alacritty/alacritty-colors.toml"]

[window]
padding = { x = 8, y = 8 }

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 13.5

[cursor]
style = { blinking = "On" }
